[2025-06-16 14:04:02,656] - database.py:62 - INFO - Getting habits...
[2025-06-16 14:04:02,657] - database.py:70 - INFO - Got habits...
[2025-06-16 14:04:02,657] - database.py:72 - INFO - []
[2025-06-16 14:04:07,601] - habits_buttons.py:46 - INFO - Пользователь вводит привычку!
[2025-06-16 14:04:59,838] - habits_buttons.py:30 - INFO - Пользователь отменил ввод привычки!
[2025-06-16 14:05:00,275] - habits_buttons.py:36 - DEBUG - Сообщение должно быть удалено!
[2025-06-16 14:05:04,553] - habits_buttons.py:46 - INFO - Пользователь вводит привычку!
[2025-06-16 14:05:08,611] - database.py:50 - DEBUG - Habit added for 582690569
[2025-06-16 14:05:08,613] - habits_buttons.py:76 - INFO - Пользователь ввел привычку!
[2025-06-16 14:05:10,486] - database.py:62 - INFO - Getting habits...
[2025-06-16 14:05:10,487] - database.py:70 - INFO - Got habits...
[2025-06-16 14:05:10,487] - database.py:72 - INFO - [(582690569, 'Зарядка', 1)]
[2025-06-16 14:06:28,847] - database.py:62 - INFO - Getting habits...
[2025-06-16 14:06:28,847] - database.py:70 - INFO - Got habits...
[2025-06-16 14:06:28,848] - habits_buttons.py:95 - INFO - ['Зарядка']
[2025-06-16 14:06:31,476] - database.py:62 - INFO - Getting habits...
[2025-06-16 14:06:31,476] - database.py:70 - INFO - Got habits...
[2025-06-16 14:06:31,477] - habits_buttons.py:95 - INFO - ['Зарядка']
[2025-06-16 14:08:27,665] - database.py:34 - ERROR - Error adding user: UNIQUE constraint failed: users.telegram_id
[2025-06-16 14:12:50,030] - database.py:34 - ERROR - Error adding user: UNIQUE constraint failed: users.telegram_id
[2025-06-16 14:25:23,763] - habits_commands.py:32 - INFO - Зашел в /add
[2025-06-16 14:25:29,032] - database.py:106 - INFO - Starting delete for 582690569:Зарядка
[2025-06-16 14:25:29,040] - database.py:115 - INFO - Successfully deleted Зарядка for 582690569
[2025-06-16 14:25:33,383] - habits_commands.py:32 - INFO - Зашел в /add
[2025-06-16 14:25:33,715] - habits_commands.py:49 - ERROR - add_habit() takes 2 positional arguments but 3 were given
